### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by swarnimarun** [mitchcurtis/slate#61]
I have a long list of features I want to see in the future of Slate, mostly important QoL improvements.
Some of the features might deserve a special issue thread but for now this is not a bad place to keep them at. 
I will add a link to the separate issue threads when there are any.

- [x] Clear layer/image on hitting Delete if nothing is already selected. #62
- [x] Duplication of Layer https://github.com/mitchcurtis/slate/issues/30
- [ ] Add PixelPerfect Brush, similar to Aseprite at the moment if we move the mouse a little fast many pixels are left uncolored. https://github.com/mitchcurtis/slate/issues/39
- [ ] Limiting Colors and adding Indexing
- [ ] Adding Filters on layers.
- [ ] Animation JSON export like Aseprite.
- [ ] Tileset editor improvements, a little long list mostly similar to Pyxel Edit.
- [ ] Grouping of Layers. 
- [ ] And, finally add some shape tools and pattern brushes and stuff.

**Comment by mitchcurtis** [comment]
Thanks for the feedback!

Feel free to push changes if you feel comfortable doing so. I do ask that auto tests be added for each new feature, but I can help with that if necessary.

Are you using Slate, by the way? I just ask because I'm curious; I don't really have any way of knowing if there are people actively using it. :)

**Comment by swarnimarun** [comment]
@mitchcurtis yeah I have been trying to use Slate just cause it's completely free. Not much though.
Other than this the only other options are Krita, Piskel and Graphics Gale(windows only).

So it makes sense to try it. I found it on the Lospec site.

**Comment by mitchcurtis** [comment]
OK, good to know. :) I would like to make it more attractive to use Slate, it's just a matter of how many features make sense and, of those, how many I'm actually able to implement. I will keep this list in mind though.

**Comment by mitchcurtis** [comment]
> Adding Filters on layers.

Is this filters like blend, drop shadow etc., or filtering as in searching through layers?

> Grouping of Layers.

What would be involved with this?

**Comment by swarnimarun** [comment]
@mitchcurtis yeah the filters will be similar, some filters are really useful for creating pixel art quickly.

And finally grouping is useful for when you create lots of pixel arts to overlay on each other. Layer Management is a big part of good usability.

**Comment by swarnimarun** [comment]
Probably we can even add layer types, like add, screen, multiply and etc.

**Comment by mitchcurtis** [comment]
> And finally grouping is useful for when you create lots of pixel arts to overlay on each other. Layer Management is a big part of good usability.

I'm more interested in what the feature does. I'm assuming you mean the ability to have sub-layers?

**Comment by swarnimarun** [comment]
The concept will be similar to grouping in Photoshop, so if we create a big piece of art then we can group the Background and then the foreground and then the other things together.

**Comment by mitchcurtis** [comment]
I've implemented the easy ones from your list. I think it would be best to have separate issues for the remaining ones so that they're easier to track, so I'll close this one.

**Comment by swarnimarun** [comment]
@mitchcurtis are you using Qt Creator, is it required?
 I am still quite inexperienced(never used it) with Qt mostly have use IMGUI for game dev tools, so have no idea how to get started fast, also have college so sometime goes there. So sorry for not being able to keep up.

I might need a little help getting upto speed with the codebase other than that it should not be a problem. 
I think it will be easy to add the animation export feature for me to get the feel of things. What do you think?
Will also write an importer for Godot for sprites and animations. Just try to make it more usable for actual game dev for which it is intended.

Just a question do we have canvas rotation? Like being able to rotate the canvas to check for mistakes?

**Comment by swarnimarun** [comment]
I really think we should also work on a Timeline for animations...

**Comment by swarnimarun** [comment]
Quick question is Qt 5.12 already out??
It's written as a dependency in the `README.md`

**Comment by mitchcurtis** [comment]
> @mitchcurtis are you using Qt Creator, is it required?

I'm using it, and would highly recommend it to make the process easier. It's not strictly required though. There is e.g. a Qt plugin for Visual Studio I think.

> I am still quite inexperienced(never used it) with Qt mostly have use IMGUI for game dev tools, so have no idea how to get started fast, also have college so sometime goes there. So sorry for not being able to keep up.

No worries, you don't have to commit to working on stuff; no pressure. :)

> I might need a little help getting upto speed with the codebase other than that it should not be a problem.

No worries.

> I think it will be easy to add the animation export feature for me to get the feel of things. What do you think?

I don't really know the feature at all, but if it's just exporting some JSON, then it sounds like it should be fairly straightforward. :)

> Just a question do we have canvas rotation? Like being able to rotate the canvas to check for mistakes?

No, not currently. What kind of mistakes would that allow checking for?

**Comment by mitchcurtis** [comment]
> I really think we should also work on a Timeline for animations...

Currently the animation is just super simple frame-by-frame stuff using an existing project. If we were to add a full-fledged animation timeline then it sounds like it would need its own new project extension. 

I'm quite happy keeping Slate on the simple side. I don't want to end up like e.g. GIMP where I end up confused and start developing my own bitmap editor. :D

> Quick question is Qt 5.12 already out??
It's written as a dependency in the README.md

No, not yet. You need to build Qt yourself if you want to use the master branch. There is a 5.11 branch too though. I can probably just cherry-pick commits from 5.11 to master.

**Comment by swarnimarun** [comment]
@mitchcurtis As for what kind of mistake rotating canvas detects is mistakes in proportions and alignment that might seem correct from a single angle, it's especially useful for a bit bigger pixel art probably 64x64 and larger.

**Comment by mitchcurtis** [comment]
> @mitchcurtis As for what kind of mistake rotating canvas detects is mistakes in proportions and alignment that might seem correct from a single angle, it's especially useful for a bit bigger pixel art probably 64x64 and larger.

Ah. Do you have any examples of applications that do this? I'm interested in trying it out and seeing how they do it. :)

**Comment by swarnimarun** [comment]
@mitchcurtis Krita does it and it's open source so look at that. Aseprite might also have it but I have not used it much.
